Add completed tasks and tests
imponomarev/Java-Backend-Course pull request #2
Opened 2023-10-15 14:42 UTC by imponomarev

2023-10-16 05:38 UTC, nexen505 requested changes

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task0.java
> +    public void helloWorld() {
Предложение: в учебных целях можно написать тест на проверку вывода логирования с использованием, например, https://github.com/stefanbirkner/system-lambda#systemout-and-systemerr

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task1.java
> +        if (seconds >= SECONDS_IN_MINUTE) {
Проблема: думаю, что отрицательное число секунд тоже надо считать некорректным, что здесь не учтено.

Предложение: добавить соответствующую логическую проверку и соответствующий тест.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task2.java
> +        while (Math.abs(num) > 0) {
Проблема: из-за данной проверки некорректно работает функция, если ей дать на вход `Integer.MIN_VALUE`.

Предложение: подумать, можно ли от этой проверки уйти.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task2.java
> +            countOfDigits = 1;
Косметика: в данном случае можно сразу делать `return` из функции.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task3.java
> +        Arrays.sort(a1);
Проблема: алгоритмическая сложность определяется сложностью сортировки, что ухудшает решение.

Предложение: изменить решение в сторону линейной сложности.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task4.java
> +            if (i + 1 == charArray.length) {
Предложение: учесть это в граничных условиях цикла для упрощения логики.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task5.java
> +        StringBuilder newDigits = new StringBuilder();
Предложение: тут и в других заданиях для оптимизации работы с памятью стоит указать размер `StringBuilder` через параметр конструктора, если этот размер можно оценить.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task6.java
> +        Integer[] digits = new Integer[strNumber.length()];
Косметика: использовать примитивный тип вместо boxed.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task6.java
> +            counter += 1;
Предложение: попробовать обойтись без дополнительного поля для упрощения.

2023-10-16 05:38 UTC, nexen505 commented on src/main/java/edu/hw1/Task7.java
> +public class Task7 {
Предложение: учесть в тестах и логике отрицательные значения сдвига.

2023-10-16 16:32 UTC, imponomarev commented on src/main/java/edu/hw1/Task0.java
> +    public void helloWorld() {
Сделал с помощью Mockito.

2023-10-16 16:33 UTC, imponomarev commented on src/main/java/edu/hw1/Task1.java
> +        if (seconds >= SECONDS_IN_MINUTE) {
Добавил проверки и тест.

2023-10-16 16:33 UTC, imponomarev commented on src/main/java/edu/hw1/Task2.java
> +        while (Math.abs(num) > 0) {
Заменил на do-while.

2023-10-16 16:35 UTC, imponomarev commented on src/main/java/edu/hw1/Task3.java
> +        Arrays.sort(a1);
Заменил сортировку массивов на функции для нахождения минимума и максимума.

2023-10-16 16:38 UTC, imponomarev commented on src/main/java/edu/hw1/Task6.java
> +        Integer[] digits = new Integer[strNumber.length()];
Сделал примитивом, но из-за этого пришлось добавить еще кода, так как для сортировки массива в порядке убывания необходимо подавать объектные типы.

2023-10-16 16:38 UTC, imponomarev commented on src/main/java/edu/hw1/Task6.java
> +            counter += 1;
Добавил функцию countKRecursive.

2023-10-16 16:39 UTC, imponomarev commented on src/main/java/edu/hw1/Task7.java
> +public class Task7 {
Учел, теперь при подаче отрицательного сдвига, число сдвигается в противоположную сторону.

2023-10-17 05:40 UTC, nexen505 approved these changes

2023-10-17 16:51 UTC, merged