Add homework2
imponomarev/Java-Backend-Course pull request #3
Opened 2023-10-22 14:34 UTC by imponomarev

2023-10-26 07:57 UTC, nexen505 requested changes

2023-10-26 07:57 UTC, nexen505 commented on src/main/java/edu/hw2/Task1.java
> +                for (int i = 1; i < power; i++) {
Проблема: теряется дробная часть показателя степени.

Предложение: воспользоваться `java.lang.Math#pow`

2023-10-26 07:57 UTC, nexen505 commented on src/main/java/edu/hw2/Task1.java
> +        public record Constant(double value) implements Expr {
Косметика: вложенные интерфейсы необязательно явно делать публичными.

2023-10-26 07:57 UTC, nexen505 commented on src/main/java/edu/hw2/Task2.java
> +public class Task2 {
Проблема: искомая проблема задания не решена.

2023-10-26 07:57 UTC, nexen505 commented on src/main/java/edu/hw2/Task3.java
> +                        connection.close();
Предложение: воспользоваться языковой конструкцией `try-with-resources`.

2023-10-26 07:57 UTC, nexen505 commented on src/main/java/edu/hw2/Task3.java
> +            throw new ConnectionException("failed to execute command: " + command);
Проблема: в задании требуются сохранять причину retry, но этого не сделано.

Предложение: привести реализацию в соответствие с заданием.

2023-10-26 07:57 UTC, nexen505 commented on src/test/java/edu/hw2/Task3Test.java
> +public class Task3Test {
Предложение: разбить задание по отдельным классам и пакетам и расширить набор тестов.

2023-10-26 18:06 UTC, imponomarev commented on src/main/java/edu/hw2/Task1.java
> +                for (int i = 1; i < power; i++) {
Заменил на Math.pow

2023-10-26 18:06 UTC, imponomarev commented on src/main/java/edu/hw2/Task1.java
> +        public record Constant(double value) implements Expr {
удалил public

2023-10-26 18:07 UTC, imponomarev commented on src/main/java/edu/hw2/Task2.java
> +public class Task2 {
Надеюсь, теперь всё корректно.

2023-10-26 18:07 UTC, imponomarev commented on src/main/java/edu/hw2/Task3.java
> +                        connection.close();
сделал

2023-10-26 18:07 UTC, imponomarev commented on src/main/java/edu/hw2/Task3.java
> +            throw new ConnectionException("failed to execute command: " + command);
Теперь сохраняется

2023-10-26 18:08 UTC, imponomarev commented on src/test/java/edu/hw2/Task3Test.java
> +public class Task3Test {
Разбил задание на отдельные классы в пакете task3. Добавил новые тесты.

2023-10-27 08:52 UTC, nexen505 approved these changes

2023-11-03 12:37 UTC, merged