Project1
imponomarev/Java-Backend-Course pull request #4
Opened 2023-10-22 18:44 UTC by imponomarev

2023-10-26 06:50 UTC, nexen505 requested changes

2023-10-26 06:50 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +        Scanner scanner = new Scanner(System.in);
Проблема: ресурс не закрывается.

Предложение: использовать языковую конструкцию `try-with-resources`.

2023-10-26 06:50 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +    private Session session;
Мысль: это поле можно заменить локальной переменной.

2023-10-26 06:50 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +            attempts++;
Проблема: повторный ввод ранее не угаданной буквы приведет к поражению.

Предложение: учесть этот сценарий и не тратить попытку пользователя при его ошибке.

2023-10-26 06:50 UTC, nexen505 commented on src/main/java/edu/project1/WordBase.java
> +        int randomIndex = (int) (Math.random() * words.length);
Косметика: код упростится с использованием `Random#nextInt(int)`.

2023-10-26 06:50 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +                break;
Косметика: здесь можно `return` делать.

2023-10-26 06:50 UTC, nexen505 commented on src/test/java/edu/project1/ProjectTest.java
> +public class ProjectTest {
Предложение: расширить набор тестов с использованием https://github.com/stefanbirkner/system-lambda#systemin

2023-10-28 14:02 UTC, imponomarev commented on src/main/java/edu/project1/ConsoleHangman.java
> +        Scanner scanner = new Scanner(System.in);
Использовал данную конструкцию

2023-10-28 14:03 UTC, imponomarev commented on src/main/java/edu/project1/ConsoleHangman.java
> +    private Session session;
Заменил локальной переменной внутри метода run

2023-10-28 14:05 UTC, imponomarev commented on src/main/java/edu/project1/Session.java
> +            attempts++;
Исправил данную ошибку, добавив список неправильно угаданных букв и проверяя alreadyGuessed

2023-10-28 14:06 UTC, imponomarev commented on src/main/java/edu/project1/WordBase.java
> +        int randomIndex = (int) (Math.random() * words.length);
Добавил Random.nextInt

2023-10-28 14:07 UTC, imponomarev commented on src/main/java/edu/project1/ConsoleHangman.java
> +                break;
Теперь делаю тут return, заканчивая игру.

2023-10-28 14:08 UTC, imponomarev commented on src/test/java/edu/project1/ProjectTest.java
> +public class ProjectTest {
Добавил несколько новых тестов, но не очень понял, какую мне сделать проверку конкретно на System.in и как.

2023-11-01 07:41 UTC, nexen505 commented on src/test/java/edu/project1/ProjectTest.java
> +public class ProjectTest {
C помощью `withTextFromSystemIn` и `tapSystemOut` можно сымитировать пользовательский ввод и прочитать вывод. Вывод можно анализировать на тему состава, ожидаемого наполнения и т.п.

2023-11-07 16:15 UTC, imponomarev commented on src/test/java/edu/project1/ProjectTest.java
> +public class ProjectTest {
Сделал тесты с имитацией пользовательского ввода и проверкой вывода.

2023-11-08 13:53 UTC, nexen505 approved these changes

2023-11-08 21:56 UTC, merged