Hw3
imponomarev/Java-Backend-Course pull request #5
Opened 2023-10-28 16:50 UTC by imponomarev

2023-10-31 13:36 UTC, nexen505 requested changes

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw2/Task1.java
> +public class Task1 {
Зря ветки друг от друга почкуешь: задание тянет за собой остальные. Лучше делать PR от master чисто по конкретному заданию. Кроме того, проверь, не нужно ли какие-то принятые PR замержить.

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw3/Task3.java
> +                for (Map.Entry<T, Integer> entry : dictionary.entrySet()) {
Проблема: у такого решения нелинейная сложность.

Предложение: добавить линейное решение с использованием `Map#merge`

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw3/Task5.java
> +            list.add(new Person(input[i].split(" ")[0], input[i].split(" ")[1]));
Проблема: если нет фамилии, разделение по пробелу даст массив из одного элемента, что сломает данный код.

Предложение: добавить тесты на такой случай и учесть в реализации.

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw3/Task5.java
> +            list = list.reversed();
Мысль: сортировку + переворачивание можно решить сортировку с "перевернутым" компаратором.

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw3/Task5.java
> +            list.sort(Person::compareTo);
Косметика: такая конструкция проще заменяется на `list.sort(Comparator.naturalOrder());`

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw3/Task6.java
> +            Queue<Stock> queue = new PriorityQueue<>(Comparator.comparingInt(Stock::getCost).reversed());
Мысль: можно сразу хранить акции в `PriorityQueue` вместо списка.

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw3/Task2.java
> +        int open = 0;
Мысль: решение можно попробовать упростить с использованием `ArrayDeque`, который позволит хранить просмотренные скобки и смотреть последнюю добавленную.

2023-10-31 13:36 UTC, nexen505 commented on src/main/java/edu/hw3/Task1.java
> +    public String atbash(String input) {
Мысль: решение значительно упростится, если не использовать мапу в таком виде, а перейти к расчету кода отраженного символа, исходя из преобразований `char` в `int`.

2023-11-07 22:04 UTC, imponomarev commented on src/main/java/edu/hw2/Task1.java
> +public class Task1 {
Хорошо! Учел это в следующих дз.

2023-11-07 22:05 UTC, imponomarev commented on src/main/java/edu/hw3/Task3.java
> +                for (Map.Entry<T, Integer> entry : dictionary.entrySet()) {
Переделал на реализацию с использованием Map.merge.

2023-11-07 22:06 UTC, imponomarev commented on src/main/java/edu/hw3/Task5.java
> +            list.add(new Person(input[i].split(" ")[0], input[i].split(" ")[1]));
Учел такую ситуацию, тесты добавил.

2023-11-07 22:06 UTC, imponomarev commented on src/main/java/edu/hw3/Task5.java
> +            list = list.reversed();
Добавил перевернутый компаратор.

2023-11-07 22:07 UTC, imponomarev commented on src/main/java/edu/hw3/Task5.java
> +            list.sort(Person::compareTo);
Заменил.

2023-11-07 22:07 UTC, imponomarev commented on src/main/java/edu/hw3/Task6.java
> +            Queue<Stock> queue = new PriorityQueue<>(Comparator.comparingInt(Stock::getCost).reversed());
Теперь храню акции сразу в очереди.

2023-11-07 22:08 UTC, imponomarev commented on src/main/java/edu/hw3/Task2.java
> +        int open = 0;
Теперь решение с использованием ArrayDeque.

2023-11-07 22:09 UTC, imponomarev commented on src/main/java/edu/hw3/Task1.java
> +    public String atbash(String input) {
Теперь рассчитываю код отраженного символа, код упростился.

2023-11-10 05:01 UTC, nexen505 approved these changes

2023-11-10 11:33 UTC, merged